### ISSUE TITLE
refresh prop on InstantSearch does not appear to function as the docs would suggest

### ISSUE THREAD

**Issue by Milesanator** [algolia/react-instantsearch#1018]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**Bug: What is the current behavior?** 
Seemingly nothing? Perhaps the cache is cleared. The onSearchState callback is not triggered when refresh is true.
The docs suggests both the cache should be cleared and a new search should be triggered: http://react-instantsearch.netlify.com/react-instantsearch/guide/refreshing_cache

**Bug: What is the expected behavior?**
A new search is triggered and the search state is updated.

**Bug: What browsers are impacted? Which versions?**
Running react in an Electron project running Electron 1.6.

**What is the version you are using? Always use the latest one before opening a bug issue.** 
v4.5.1

**Comment by samouss** [comment]
When the cache is refresh a new search is triggered but the searchState is not updated. We don't need to update the searchState since we only clear the cache for the previous queries.

You can inspect the network tab in our [Storybook](https://community.algolia.com/react-instantsearch/storybook/?selectedKind=RefreshCache&selectedStory=with%20a%20refresh%20button&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs) example. When you click on the refresh button a new search is triggered and all previous search are not in cache anymore.
