### ISSUE TITLE
Remove old pages from GitHub pages

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#1091]
https://community.algolia.com/react-instantsearch/widgets/MultiRange.html for example still exists, from v4, and those should probably 404 instead

**Comment by samouss** [comment]
I think there was an issue when we erase the previous version because I remember a commit of @vvo about that.

> https://github.com/algolia/react-instantsearch/pull/444

**Comment by vvo** [comment]
Context on #444:
- when building a new version of the website
- new SHAs are computed for CSS files (index-321321321...css)
- when pushing to GH pages, you have two choices:
 1. erase everything/publish
 2. only add, never remove

We chose 2. otherwise previously built CSS file is removed, and in some cases, you will load the HTML page of the website, it will be an old version in cache of cloudflare, but the CSS will have disappeared.

Best option would be not to remove MultiRange and throw a 404, but to keep it empty like RangeSlider, and redirect to the new way to implement it (renamed).

WDYT?

**Comment by Haroenv** [comment]
Yep, makes sense, let's add redirects for all the renamed things @samouss ?

**Comment by Haroenv** [comment]
The site no longer exists
