### ISSUE TITLE
Search query resets on nbHits === 0

### ISSUE THREAD

**Issue by Bouncey** [algolia/react-instantsearch#1097]
**Bug: What is the current behavior?**

When no results are found, the search query resets to a `falsy` value

**Bug: What is the expected behavior?**

The search query remains in `searchState`

**What is the version you are using? Always use the latest one before opening a bug issue.**

v5.0.1

Reproduce from [this repository](https://github.com/freeCodeCamp/search-assets)

### Steps to reproduce:

1. Clone the above linked repository
1. `cd` into the `www/` directory 
1. `npm|yarn install`
1. `npm run|yarn develop`
1. enter a query until you receive no hits

### GIF

![anim](https://user-images.githubusercontent.com/18572518/37721720-2c7dea8c-2d22-11e8-8dd8-1c2c83ae1d1c.gif)

### Connected Components

Apart from these components, all other `react-instantsearch` components are implemented straight out of the box.

```jsx 
// src/components/SearchHits.js 
import React from 'react';
import {
  connectStateResults,
  connectAutoComplete
} from 'react-instantsearch/connectors';
import isEmpty from 'lodash/isEmpty';

import { makeResult } from './Result';
import EmptySearch from './EmptySearch';
import NoResults from './NoResults';

import './hits.css';

const attributes = {
  challenges: ['title', 'description'],
  guides: ['title', 'content'],
  youtube: ['title', 'description']
};

const ChallengeHit = makeResult(...attributes.challenges);
ChallengeHit.displayName = 'ChallengeHit';

const GuidesHit = makeResult(...attributes.guides);
GuidesHit.displayName = 'GuidesHit';

const YoutubeHit = makeResult(...attributes.youtube);
YoutubeHit.displayName = 'YoutubeHit';

const hitCompMap = {
  challenges: ChallengeHit,
  guides: GuidesHit,
  youtube: YoutubeHit
};

const blockTitleMap = {
  challenges: 'Lessons',
  guides: 'Guide',
  youtube: 'YouTube'
};

const AllHits = connectAutoComplete(
  ({ hits, handleSubmit }) =>
    hits.length ? (
      <div className="ais-Hits">
        {hits.map(({ hits: results, index }) => {
          const HitComponent = hitCompMap[index];
          return (
            <div className="hits-block-wrapper" key={index}>
              <div className="hits-block-title">
                <h4>{blockTitleMap[index]}</h4>
              </div>
              <ul className="ais-Hits-list">
                {results.map(result => (
                  <li
                    className="ais-Hits-item"
                    data-fccobjectid={result.objectID}
                    key={result.objectID}
                  >
                    <HitComponent handleSubmit={handleSubmit} hit={result} />
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>
    ) : null
);

AllHits.displayName = 'AllHits';

const SearchHits = connectStateResults(
  ({ handleSubmit, searchResults, searchState }) => {
    const isSearchEmpty = isEmpty(searchState) || !searchState.query;
    const results = searchResults && searchResults.nbHits !== 0;

    return isSearchEmpty ? (
      <EmptySearch />
    ) : results ? (
      <AllHits handleSubmit={handleSubmit} />
    ) : (
      <NoResults query={searchState.query} />
    );
  }
);

SearchHits.displayName = 'SearchHits';

export default SearchHits;
```
```jsx
// src/components/Result.js

import React from 'react';
import PropTypes from 'prop-types';
import { connectHighlight } from 'react-instantsearch/connectors';

// TODO: Shorten the highligh to max 144 chars

const ShortenedHighlight = connectHighlight(({ highlight, attribute, hit }) => {
  const parsedHit = highlight({
    attribute,
    hit,
    highlightProperty: '_highlightResult'
  });
  const highlightedHits = parsedHit.map((part, i) => {
    if (part.isHighlighted) {
      return (
        <mark key={`result-${hit.objectID}-${attribute}-${i}`}>
          {part.value}
        </mark>
      );
    }
    return part.value;
  });
  return <span key={`result-${hit.objectID}`}>{highlightedHits}</span>;
});

export const makeResult = (...attributes) => {
  const MadeResult = ({ hit }) => {
    const [title, body] = attributes;
    return (
      <div className="result-block">
        <h4>
          <ShortenedHighlight attribute={title} hit={hit} />
        </h4>
        <hr />
        <p>
          <ShortenedHighlight attribute={body} hit={hit} />
        </p>
      </div>
    );
  };
  MadeResult.displayName = 'MadeResult';
  MadeResult.propTypes = {
    hit: PropTypes.object
  };
  return MadeResult;
};
```

**Comment by Haroenv** [comment]
Thanks for this elaborate issue, this definitely seems like a bug

**Comment by Bouncey** [comment]
Further notes:

- If a `defaultRefinement` is provided to `SearchBox`, the query resets to this. My understanding was `defaultRefinement` is only used on mount?
- The code provided in the OP has changed slightly, but the issue still remains.

**Comment by samouss** [comment]
@Bouncey I looked at the code the problem come from the fact that the `<AllHits />` widget is unmount when you don't have results. In React InstantSearch in order to have a refinement applied the widget must be mounted on the page. In your case the `<SearchBox />` & `<AllHits>` share the same part of the state which is the query. When you don't have results the widget is unmount and so the query is removed. 

There are severals possible solutions to avoid the issue but I would like to understand your use case first. What do you want to build? On the GIF we saw an instant results page but right now on the repo it the App looks like an autocomplete. In the first case you should not use `connectAutoComplete`. You can wrap a custom widget built with `connectHits` under the `<Index>` component. The `SearchBox` in the header will search in all the indices and your hits will be correct displayed.

```jsx
const CustomHits = connectHits(...);

const AllHits = () => (
  <Fragment>
    <Index indexName="challenges">
      <CustomHits />
    </Index>
    <Index indexName="guides">
      <CustomHits />
    </Index>
    <Index indexName="youtube">
      <CustomHits />
    </Index>
  </Fragment>
);
```

In the second case you can get rid of the `SearchBox` in the header and replace it with a custom widget built with `connectAutocomplete`. You can still display the results inside the page with the above solution. You can find more information about that [in our documentation](https://community.algolia.com/react-instantsearch/guide/Autocomplete_menu.html).

Happy to make an PR on your project if you need some help to implement those solutions.

**Comment by Bouncey** [comment]
It would be awesome if you could raise a PR! 

All we want is a results list where users can click through to the content that has been found. We are starting off very basic just to get an MVP. 

The only reason I went with `connectAutocomplete` because it gave me the hits from the three indices's in one place. I didn't know it unmounts when no results are returned.

**Comment by samouss** [comment]
I made a PR with an autocomplete in your project. The implementation is very basic, it's just an example. I replace the main `<SearchBox />` with an `<Autocomplete />` component built with `connectAutoComplete`. You don't need to render the results in the page since they are rendered in a kinda dropdown list. The click is not enable I simply log the element clicked in the console.

**Comment by samouss** [comment]
@Bouncey Does it solve your issue?

**Comment by Bouncey** [comment]
Yes, thank you @samouss once again :+1:
