### ISSUE TITLE
Having the search state compatible with all our other libraries

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#111]
Use case:

For example, you're using React-InstantSearch for a web application and a native mobile client for the mobile app. Right now, there's no way to share the state between those app. It means that RIS can't provide enough information to build the state that is needed for the native client. 

Proposal:

TBD

**Comment by vvo** [comment]
Yes for this, being able to express the state of a search UI in a common way in all our InstantSearch libraries and being able to serialise this state to either helper or REST API requests is key for the future of InstantSearch.

**Comment by sarahdayan** [comment]
Hey!

We're doing a round of clean up before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately and to be mostly solved, so we're going to close it.

Both React InstantSearch and React InstantSearch Hooks accept an initial state:

- [React InstantSearch](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-searchstate)
- [React InstantSearch Hooks](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react-hooks/#widget-param-initialuistate)

The `initialUiState` prop is serializable, so you can easily share it between implementations (e.g., web and native).
