### ISSUE TITLE
Unable to use <ClearAll /> with <SortBy /> component

### ISSUE THREAD

**Issue by trangiiee** [algolia/react-instantsearch#1182]
Hello!

Thank you so much for making such a wonderful search app. It's really great! I'm having an issue that I'm not sure how to address. Any assistance would be appreciated.

## What is the current behavior?

I am unable to reset the `<SortBy />` components to the default state using the `<ClearAll />` component.

Example: https://codesandbox.io/s/vm9o75rpn7

**Comment by samouss** [comment]
Thanks a lot for the reproduction of the issue. Indeed we don't support the reset of `<SortBy>` with the `<ClearAll>` component. It's because (internally) we don't consider the sort behaviour as a refinement. We plan to support it in a next version.

In the meantime, I built a example with the connectors API that show how you can implement this functionality. Keep in mind that it's very basic implementation (for example the button is not disabled when we don't have refinements). You can find the example on [CodeSandbox](https://codesandbox.io/s/l5jo5ypjjz).

**Comment by trangiiee** [comment]
Thank you @samouss!
