### ISSUE TITLE
Selecting an range between 2 values across 2 fields.

### ISSUE THREAD

**Issue by PatchOnKnee** [algolia/react-instantsearch#1313]
**Do you want to request a *feature* or report a *bug*?**
Not sure, possibly feature

**Feature: What is your use case for such a feature?**
I want to be able to input a filter using comparison operators. Using something akin to the range operator from the filters API reference:

https://www.algolia.com/doc/api-reference/api-parameters/filters/?language=javascript#numeric-filters

Doing this across multiple attributes in a index would also be helpful. The need for this stems from having 'events' in my index, with a starting date (startDate) and an ending date (endDate). I want the user to be able to input two dates and then receive all the events that would have a day within these ranges. Currently the dates are stored in UNIX time stamp format, hence the idea to use comparison operators. 

Thanks for the great package

**Comment by Haroenv** [comment]
Hey @PatchOnKnee, this is indeed not too trivial of a use case. A month ago or so I made something with @samouss to work with dates (inclusive and exclusive), but it hasn't made its way back as a core API since we were thinking about naming a lot. Note the `restrictResultsToStrictRange` prop given. See the sandbox here: https://codesandbox.io/s/kwklo3rz63

Does that solve what usage you had in mind?

**Comment by samouss** [comment]
I'm closing this one since it's inactive, feel free to re-open an issue.
