### ISSUE TITLE
Sync an AutoComplete with the rest of the search

### ISSUE THREAD

**Issue by marcobiedermann** [algolia/react-instantsearch#1396]
I've noticed that if you select something using the autocomplete searchbox, the results (hits) won't get updated: https://codesandbox.io/embed/github/algolia/react-instantsearch/tree/master/examples/autocomplete

Simply add the `<Hits />` component and see the result after selecting something via searchbox.

![image](https://user-images.githubusercontent.com/5244986/41963957-21ba194e-79f9-11e8-8451-df83047ac594.png)

No matter what you select, it will only show the "LEGITIM" product

**Comment by samouss** [comment]
Yes indeed it's because once the value is selected `react-autosuggest` clear the suggestions. Since the suggestions are cleared React InstantSearch will reset the hits to the empty query. You can still access the selected value with the callback [`onSuggestionSelected`](https://github.com/moroshko/react-autosuggest#onSuggestionSelectedProp).

The usage of the an autocomplete may differ from one implementation to another. Most of the time the suggestions are in a different index so we don't have the issue with the reset. The hits displayed are scoped under their own index and are independent from the autocomplete. Then once the value is selected you can sync the main index with the selected value. You can sync the two instance with [the mode controlled](https://community.algolia.com/react-instantsearch/guide/Routing.html) of React InstantSearch. We have [an example](https://github.com/algolia/react-instantsearch/tree/master/examples/react-native-query-suggestions) that implement this pattern in React Native. It's a different renderer that React DOM but the concepts remains the same. In case the suggestions are in the same index you can use two different instances of React InstantSearch then sync them in the same way than we do when we have multiple indices.

**Comment by samouss** [comment]
I'm closing this issue, feel free to re-open one.
