### ISSUE TITLE
connectRange with numericAttributesForFiltering

### ISSUE THREAD

**Issue by chenhoward** [algolia/react-instantsearch#1406]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
I want to be able to use the rangeInput for numericAttributesForFiltering (that I set through the JS API). 
When I manually remove the disable attribute, the rangeInput works correctly.
The reason I don't make it a facet is that it would explode the data size.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
Keep the same API, just update the canRefine check.

**What is the version you are using? Always use the latest one before opening a bug issue.**
5.1.0

**Comment by samouss** [comment]
Thanks for the feedback! I didn't get what you meant by "explode the data size". You are talking about the size of the Algolia response? Did you actually tried to use this attribute as `attributeForFaceting` rather than `numericAttributesForFiltering` ? I ask those questions to have a bit more context.

The thing is that in the `connectRange` connector we heavily rely on `facet_stats` (for the placeholders for example). Those values are computed from the facet but with `numericAttributesForFiltering` we don't have access to those values. 

Right now a possible solution is to implement [a custom connector](https://community.algolia.com/react-instantsearch/guide/Custom_connectors.html). The implementation should be pretty straight forward though. You can take a look at the implementation of [`connectRange`](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectRange.js) or [`connectDateRange`](https://codesandbox.io/s/kwklo3rz63) as an example.

**Comment by chenhoward** [comment]
Thanks for the response @samouss! What I mean about the data size was that making it a attributeForFaceting increases our index size over the size of the cluster because of the high cardinality of the column I'm trying to query against.

Thanks for pointing me in the direction of the custom connector, will check it out.

**Comment by samouss** [comment]
Okay thanks for your feedback. 

I'll close the issue since there is nothing we can do about it right now. But I've send the feedback to our product team! Don't hesitate to open a new one if we have issue with the custom connector.
