### ISSUE TITLE
Server side rendering with custom backend fails with server side error

### ISSUE THREAD

**Issue by spanditcaa** [algolia/react-instantsearch#1442]
**Bug: What is the current behavior? Server side error on the initial request for the site.  The custom search function passed on instantSearch is being executed on the server.

**Bug: What is the expected behavior?  Page renders normally and the custom search function is executed on the client.

**Bug: What browsers are impacted? Which versions? all.  Error is server side.  Tested with node 10.6.0

I've set up an example using https://github.com/algolia/react-instantsearch/tree/master/examples/server-side-rendering and configured a custom backend per https://community.algolia.com/react-instantsearch/guide/Custom_backend.html.  This can be found at https://github.com/spanditcaa/instantsearch-ssr-custombackend.

When you hit the site, the node process returns the following error: 

````
(node:52446) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
````

This is happening because the custom search function is being executed, server side for the initial render.  I believe we need a way to pass the custom search client to createInstantSearch() instead of using the searchClient option for instantSearch.

**Comment by francoischalifour** [comment]
Hi there, [the `fetch` module used](https://github.com/spanditcaa/instantsearch-ssr-custombackend/blob/master/src/app/index.js#L13) is only available in the browser and therefore is not defined on Node (as you're doing SSR). You could use any `fetch` alternative like [Axios](https://github.com/axios/axios).

**Comment by spanditcaa** [comment]
using Axios yields the same issue @francoischalifour - we don't want the custom search function to be called in the initial server side render - we need the method passed down to the client so it knows how to make subsequent requests.

**Comment by samouss** [comment]
The initial call on the server is the expected behaviour. This is the all purpose of doing SSR with React InstantSearch. We do the first request on the server to provide a static page to the browser. It allows the user to have a faster response (most of the time). Once the static page is rendered React take the leads and re-use the already generated markup to avoid to render the page a second time. I've opened [a PR](https://github.com/spanditcaa/instantsearch-ssr-custombackend/pull/1) on your example in order to have a working example with Axios (since `fetch` is not available in Node).

**Comment by spanditcaa** [comment]
Understood and thank you @samouss, confirmed you fixed my broken example.
