### ISSUE TITLE
React.StrictMode compatibility

### ISSUE THREAD

**Issue by denkristoffer** [algolia/react-instantsearch#1743]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Feature: What is your use case for such a feature?**

With concurrent React being worked on, I figured it'd be a good idea to officially request that React InstantSearch becomes [StrictMode compatible](https://reactjs.org/docs/strict-mode.html) 🙂

**Comment by Haroenv** [comment]
Thanks for the official feature request. We are aware of the issue, but we have not done this yet, since it requires **major** changes in the way we make the library. The main problem is that we _rely_ on all the deprecated life cycles, and since we didn't find a proper way to do these changes in a non-breaking way (we can try out [react-lifecycles-compat](https://github.com/reactjs/react-lifecycles-compat)).

We will definitely work on this, but it has not yet been the highest priority so far.

**Comment by cloakedninjas** [comment]
> we didn't find a proper way to do these changes in a non-breaking way

I don't think anyone would mind if React 17 compatibility was done with a SEMVER major bump

**Comment by samouss** [comment]
We're working on a new major version that will be compliant with the strict mode of React. We don't have any ETA but we are already pretty far in our migration. Note that this version won't have any hook implementation. It will only contain changes related to strict mode.

**Comment by Haroenv** [comment]
This has been implemented in the next major version of React InstantSearch, version 6 which is currently in beta. You can find information on this here: https://discourse.algolia.com/t/react-instantsearch-v6-beta-0-released/8308
