### ISSUE TITLE
RatingMenu: Allow rating multi-selection

### ISSUE THREAD

**Issue by mufudzimasaire** [algolia/react-instantsearch#1755]
The rating menu currently does not support multi-selection. 

It would be nice to have this feature, as the workarounds available are not great:

**Option 1:**  Using the `RefinementList#transformItems` function, you can bastardise the label into displaying the  stars by passing a list of elements.

![ratings](https://user-images.githubusercontent.com/4486874/48837621-b8af6f00-ed7d-11e8-937b-fca96f240b72.png)

Though this workaround works (well to an extent), you still get the following warning, as the item label prop type is restricted to strings:

![console_warning](https://user-images.githubusercontent.com/4486874/48837587-aaf9e980-ed7d-11e8-9619-ec754a6b5eed.png)

**Option 2:** Another workaround using the `RefinementList` is to define a custom `template`. However, the `RefinementList` component in the `react-instantsearch-dom` package does not currently support `templates` - https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-dom/src/components/RefinementList.js#L12

**Comment by Haroenv** [comment]
What you can do is make a complete custom refinement list with `connectRefinmentList`, it wouldn't really make sense to try to shoehorn this behaviour into the regular rating component; since it will act as "x & up", so multiple selections aren't possible. 

a connector is a higher order component, giving access to `items`, and `refine` which you can use to render the list and as click handler for the input. 

Read more:

- https://community.algolia.com/react-instantsearch/guide/Connectors.html
- https://community.algolia.com/react-instantsearch/connectors/connectRefinementList.html

**Comment by mufudzimasaire** [comment]
Many thanks for the prompt reply @Haroenv, will look into it 👍
