### ISSUE TITLE
Refinements applied in modal are cleared on close, virtual widget doesn't appear to be working?

### ISSUE THREAD

**Issue by rtman** [algolia/react-instantsearch#1776]
Hi,

So for my web app I want to put our refinements in a modal. I've followed the guide for doing this and still the refinements applied in the modal are cleared when the modal is closed. Maybe I've made a mistake or am using the Virtual Widget incorrectly??

I also notice a significant slowdown when passing searchstate and onSearchStateChanged between the two InstantSearch instances. If I comment out those two props on the 1st instance the slowdown disappears. This effect isn't as noticeable in the codesandbox but in my actual app the slowdown is severe.

Here is my codesandbox illustrating the issue.

https://codesandbox.io/s/3y7kw953ym

**Comment by samouss** [comment]
The state of the `RefinementList` inside the modal is not persisted because the `onSearchStateChange` callback only apply the current state. Inside our [React Native example](https://github.com/algolia/react-instantsearch/blob/3fc8fb977701db3df8408789bd6dabecda7290db/examples/react-native/src/Home.js#L126-L128) we do merge the previous and the current state. Here is [your example](https://codesandbox.io/s/o59jvqop5q) updated.

**Comment by rtman** [comment]
Ah ok, I wasn't following another guide from the react-instantsearch docs on your site which doesn't have `prevState` merging. Can you guys update the [docs](https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#putting-our-filters-in-a-modal) ?

**Comment by samouss** [comment]
We are in the process of re-writing the full documentation, this issue will be fixed at that time. Thanks for spotting the issue though!
