### ISSUE TITLE
Package a Range component

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#18]
# Use case

Today, to have a Range widget with React InstantSearch you need to build your own, or use an external component. We provide several code sample to show how this can be achieved using `rheostat` from airbnb. 

# Need

This code sample is getting pretty big right now and it would be better to propose to our user a packaged Range component, ready to use outside of the box. 

# Proposal

TBD. 

We got two options here: either we built our own again, or we use `rheostat` or `rc-slider` but with a limited api.

**Comment by sarahdayan** [comment]
I'm going to close this issue since we don't use GitHu to centralize feature requests.

@seafoox Pinging you so you're aware of it, if there's any demand for an out-of-the-box range slider cmponent. Note that we don't provide any either for React InstantSearch or React InstantSearch Hooks for now. If we ever consider it, we'd do it for Hooks only.
