### ISSUE TITLE
Duplicate refinements in CurrentRefinements with multiple times same widget

### ISSUE THREAD

**Issue by josephkandi** [algolia/react-instantsearch#1967]
**Describe the bug 🐛**

On my page i have two `MenuSelect` components in different locations on the page. When i click on a selection on the `MenuSelect`, i do get duplicate labels in the `CurrentRefinements`

**To Reproduce 🔍**

Add two `MenuSelect` components on the page with a `CurrentRefinement` component as well

A live example helps a lot! We have a simple online template for you to use for your explanations:

> https://codesandbox.io/s/53571y85mk

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/3235272/52013330-6ad58680-24e5-11e9-9eed-eaa0cbe22428.png)

**Comment by samouss** [comment]
Yes it's the expected behaviour with our current API. You can get rid of the duplicate refinements with [`transformItems`](https://www.algolia.com/doc/api-reference/widgets/current-refinements/react/#widget-param-transformitems) on `CurrentRefinements`. Here is [an example](https://codesandbox.io/s/pj300jpr2q) that show how to implement it.

**Comment by josephkandi** [comment]
Ok thanks

**Comment by benfavre** [comment]
Why purposely make the lib bad ?
