### ISSUE TITLE
Add a HierarchicalBreadCrumb widget

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#23]
The helper is able to give us the Hierarchical Facet BreadCrumb through https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#getHierarchicalFacetBreadcrumb

We should add a new widget/connector that allow a user to add this into its website. 

- [x] Propose an API for the connector (Provided Props / Exposed Props)
- [x] Propose an API for the widgets 
- [x] Propose a default style 
- [x] Decide if we go for an option within the connectHerarchicalMenu or with a new connector. 
- [x] Implement connector
- [x] Implement widgets
- [x] Add stories
- [x] Document the need for a virtual Hierarchical Menu for the default refinement

**Comment by mthuret** [comment]
https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/

**Comment by marielaures** [comment]
# ConnectBreadcrumb

## Exposed props

- attributes : List of attributes to use to generate the hierarchy of the menu. See the example for the convention to follow.
- separator : Symbol used for separating hyperlinks
- rootURL : The originating page (homepage)
- transformItems: Function to modify the items being displayed, e.g. for filtering or sorting them. Takes an items as parameter and expects it back in return.

## Provided props

- refine: A function to toggle a refinement
- createURL: A function to generate a URL for the corresponding search state
- items: the list of items the Breadcrumb can display

**Comment by marielaures** [comment]
## Breadcrumb (Widget)

## Description
A breadcrumb is a secondary navigation scheme that allows the user to see where the current page is in relation to the website or web application’s hierarchy.
In terms of usability, using a breadcrumb reduces the number of actions a visitor needs to take in order to get to a higher-level page.

## Props
- attributes: List of attributes to use to generate the hierarchy of the menu. See the example for the convention to follow. (type: string)
- separator: Symbol used for separating hyperlinks. (type: string or React Component). (default: " > ")
- rootURL: the root element's URL (the originating page). (type: string) (default: null)
- transformItems: Function to modify the items being displayed, e.g. for filtering or sorting them. Takes an items as parameter and expects it back in return.

## Requirements
Breadcrumbs are used for websites with a large amount of content organised in a hierarchical manner. The typical example is an e-commerce website which has a large variety of products grouped into logical categories (with categories, subcategories which also have subcategories).

Keep in mind that breadcrumbs shouldn’t replace effective primary navigation menus: it is only an alternative way to navigate around the website.

## Example usage

## CSS classes

## Translation keys

**Comment by marielaures** [comment]
This is the first version of the Breadcrumb component I've been working on! Happy to have any feedback :) @mthuret @Haroenv @vvo

**Comment by Haroenv** [comment]
Overall this looks good to me, it's a good idea to call it `Breadcrumb` instead of `HierarchicalBreadcrumb`. A question I have is how to deal with the levels that are visible. Do you start to roll over to the deepest one after `visibleLevel` or something would be reached? Doing that would make it really nice to support smaller screens, where we maybe only want to have two levels visible. The user could then deal with truncation in CSS or with the connector in JS

**Comment by vvo** [comment]
Nice API doc!

What is the purpose of `rootURL`?

**Comment by Haroenv** [comment]
@vvo that's the root of all links if you want to have a complete url instead of `/some/things`, right? I wonder if we can't just make it relative by default (If I understand it correctly)

**Comment by marielaures** [comment]
Yes @vvo @Haroenv usually on websites, people have a "Home" label as the root of their breadcrumb (screenshot attached).
By default, it refines with the empty query but you can also add the URL of your choice
![screen shot 2017-08-03 at 10 14 28](https://user-images.githubusercontent.com/21305268/28912504-cb6825ca-7834-11e7-9db6-badebe68fe56.png)

**Comment by vvo** [comment]
Got it, thanks! So when you do not provide rootURL there's no "HOME" added right?

**Comment by marielaures** [comment]
For now, "Home" is always displayed: it either refines with the empty query, or it redirects to the `rootURL` provided by the user if any!

**Comment by mthuret** [comment]
In term of use case: you got a website with an autocomplete on its homepage that displays some categories. If you click on one of those categories you are redirected to the instant search page with some refinements pre-made. But then, you don't want you're "Home" root label to perform an empty query and stay on an instant search page, but rather go back to the root or another fix page. Does it makes sense?

**Comment by vvo** [comment]
Yes it makes sense

**Comment by mthuret** [comment]
Present in 4.1.0-beta.5.
Will be release as a stable version soon.
