### ISSUE TITLE
can not open example in new expo

### ISSUE THREAD

**Issue by craigcosmo** [algolia/react-instantsearch#2337]
I'm ruunning expo latest

When init the exmaples I got this error

![Screen Shot 2019-04-17 at 4 27 23 PM](https://user-images.githubusercontent.com/538657/56277068-d49d1e00-612d-11e9-9eee-d654ef364c94.png)

**Comment by samouss** [comment]
Hi, which example you've run exactly? The one inside the [project](https://github.com/algolia/react-instantsearch/tree/master/examples/react-native)? We're in the process to rewrite them because they rely on an outdated version of Expo, here is the [PR](https://github.com/algolia/react-instantsearch/pull/2304) for it. In the meantime you can follow our [Getting Started](https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/) on React Native. The final example hosted on GitHub does not work for the same reason, but you can follow the steps to build the `App`.

**Comment by Haroenv** [comment]
Hi! This issue has been opened without reply for a while. I'll close it now, but feel free to reply to our initial questions, and we'll gladly reopen if the original issue isn't solved yet.

Have a nice day!
