### ISSUE TITLE
[Question] Do you have high order component to populate unique method to clear all refinements and applied sorting to default values.

### ISSUE THREAD

**Issue by vcernomschi** [algolia/react-instantsearch#2490]
Do you have high order component or more elegant way to populate unique method to clear all refinements and applied sorting to default values.

I am asking as in API reference I found out the 2 separate connectors:
- connectSortBy based on https://www.algolia.com/doc/api-reference/widgets/sort-by/react/#connector
- connectRefinementList based on https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#connector 

These 2 HOCs have refine method and items, so I added HOC to rename methods to be able to call both of them onClick event to refine current refinements and change sorting to defaultRefinement value.

So my solution doesn't look quite elegant for me, so just wanted to clarify how usually you resolve this scenario?

**Comment by Haroenv** [comment]
There's a connector `connectCurrentRefinements`, which also allows clearing refinements: https://www.algolia.com/doc/api-reference/widgets/clear-refinements/react/#connector

However it doesn't reset sort, since this is not something that has come up for us before. You'll still need two connectors for that.

**Comment by vcernomschi** [comment]
Thanks @Haroenv
