### ISSUE TITLE
Multiple RangeSliders values wrong

### ISSUE THREAD

**Issue by alextrastero** [algolia/react-instantsearch#2721]
**Describe the bug 🐛**

When I add TWO `connectRange` components with different `attributes` the values returned from algolia are wrong when using sliders.

**To Reproduce 🔍**

It is not possible to reproduce with the sandbox due to only one facet can be refined with a range slider; price. 

But this is the idea:
My current sandbox: https://codesandbox.io/s/ais-ecommerce-demo-app-o1li6

**Screenshots 🖥**

![foo](https://user-images.githubusercontent.com/4152819/62124611-f2e8ed00-b2ca-11e9-9dbf-1d31fe39b1f1.png)

**Environment:**

 - OS: mac
 - Browser chrome
 - Version latest

**Comment by samouss** [comment]
The attributes `min`/`max` and `currentRefinement` provided by the connector does not represent the same values. `currentRefinement` is the value refined by the user. The `min`/`max` values are computed from Algolia. It might happen that a user select a range, then apply filters and get results that don't match the given range. It's not because we don't have results that match the current criteria that we don't have results at all.

From what I've understood from the screenshot the refinement applied by the user is 466638 but the maximum value retrieved is 188391. To find this result we use disjunctive faceting. Under the hood React InstantSearch trigger an additional query without the filter on `total_followers` to get the `min`/`max` values. The same concept is applied to `Menu`, `RefinementList`, ...

You'll probably have to adapt your slider implementation to this behaviour.

**Comment by alextrastero** [comment]
Thanks for the reply @samouss, I'm going to use another component in this case.
