### ISSUE TITLE
TypeScript - findResultsState is not defined

### ISSUE THREAD

**Issue by AjithRithik** [algolia/react-instantsearch#2900]
Hi, 

I am trying to fetch the **Instantsearch** result from **ssr** using **finalResultstate** from 

> "react-instant-search dom/server"

But I am getting the error like 

> "@types/react-instantsearch-dom/server"' has no exported member 'findResultsState'

I've attached error screenshot also.

can anyone help me to resolve this issue? Thanks in advance...
<img width="903" alt="Screenshot 2020-03-13 at 12 22 36 AM" src="https://user-images.githubusercontent.com/43243561/76557327-5eca3f80-64c1-11ea-8d0d-7e9efff41434.png">

**Comment by Haroenv** [comment]
Hi! This is because DefinitelyTyped still has the typings for React InstantSearch v5, while you're using React InstantSearch v6. I've updated the types just now in this pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43111

In the mean time before that's published, you can suppress the error with `// @ts-ignore`

**Comment by Haroenv** [comment]
This has been published since :)
