### ISSUE TITLE
The react native example is very outdated and not build successfully

### ISSUE THREAD

**Issue by MoeMamdouh** [algolia/react-instantsearch#2908]
The react native example is very outdated and not build successfully
the old react native and expo version used 

`"expo": "32.0.6",`

also used an outdated component like `ListView`

```

 const ds = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2,
    });
    const hits =
      this.props.hits.length > 0 ? (
        <View style={styles.items}>
          <ListView
            dataSource={ds.cloneWithRows(this.props.hits)}
            renderRow={this._renderRow}
            renderSeparator={this._renderSeparator}
            onEndReached={this.onEndReached}
          />
        </View>
      ) : null;
    return hits;
```

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it.

Since then, we updated the react native examples to more recent versions of expo, and are using `FlatList` instead of `ListView`.
