### ISSUE TITLE
RefinementList searchAsYouType prop

### ISSUE THREAD

**Issue by w0nche0l** [algolia/react-instantsearch#2925]
**Is your feature request related to a problem? Please describe 🙏**
I am trying to avoid incurring too many operations. I am trying to minimize operation count by disabling some quality of life features. 

**Describe the solution you'd like 🤔**
I would like a prop on RefinementList that works similarly to searchAsYouType, where the user needs to hit enter to see the results. 

**Describe alternatives you've considered ✨**
I would have to make another RefinementList using the connectors. If there are other alternatives, please let me know. 

**Additional context**
I'm looking for general advice on minimizing operation count. Are there any features I can disable that make a big impact?

**Comment by eunjae-lee** [comment]
Hi there,
if you pass `false` to `searchAsYouType`, then it's exactly what you want. Only hitting enter will refine the search results.

https://codesandbox.io/s/serene-bas-eksth?file=/src/App.js:1098-1121

And you can also debounce the search by using the connector(https://github.com/algolia/react-instantsearch/issues/970)

For operation count in general, do you already have a big number that you wish to decrease?

**Comment by w0nche0l** [comment]
Hi, sorry, I was asking about having a similar prop on the **RefinementList**, not the SearchBox.

Not necessarily, but I was noticing while playing around that there are a lot of calls to the API. I would be very interested in being able to use the UI without updating the search results at ALL until you hit "search".

**Comment by Haroenv** [comment]
Sorry, this is not a feature we have by default, since it can leave the search in an inconsistent state (e.g. other facet counts that should change when you select something). 

The way to go for such custom behaviour is to make custom widgets which are linked together to refine only on a submit button. A  simplified example of this approach is: 

- https://codesandbox.io/s/react-instantsearch-app-s3snq
- https://codesandbox.io/s/react-instantsearch-app-lcnyk

**Comment by Haroenv** [comment]
We don't have this feature out of the box, as the UX is subpar, a custom widget can be written that debounced the call to `searchForValues`
