### ISSUE TITLE
Next.js SSR - TypeError: Cannot read property 'replace' of undefined - version: 6.7.0

### ISSUE THREAD

**Issue by francisrod01** [algolia/react-instantsearch#2958]
**Describe the bug 🐛**

Seems like the version `6.7.0` has a bug related to results state when implementing it by server-side rendering in Next.js applications. https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react/

**To Reproduce 🔍**

1. Update the package to `6.7.0`.
2. Implement `findResultsState` on `getInitialProps` or `getServerSideProps` functions.

```
TypeError: Cannot read property 'replace' of undefined
    at removeDuplicateQuery (/home/paneladm/projects/paneladm-dev/medina-app/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:83:17)
    at /home/paneladm/projects/paneladm-dev/medina-app/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:96:15
```

## Environment that buged

- node: 10.20.1
- npm: 6.14.4
- algoliasearch: `4.3.1`
- react-instantsearch: `6.7.0`

### Environment that worked

- node: 10.20.1
- npm: 6.14.4
- algoliasearch: `4.3.0`
- react-instantsearch: `6.6.0`

### Live example on Codesandbox.io

A live example working: https://codesandbox.io/s/nextjs-instantsearch-ohphp

**Comment by Haroenv** [comment]
I understand where this bug comes from (removeDuplicateQuery), but have not yet pinpointed in which situation this error can occur in your example. I've updated it to React InstantSearch v6.7.0 and have tried both a search without query parameters and with query parameters, but both seem to work. Which case does this happen in?

**Comment by Haroenv** [comment]
I've investigated, and do not find a case where this error can be thrown. I'm inclined to think that if `params` is undefined, something else is also not working as expected, meaning the problem comes from somewhere else. In the example you gave, I can't see a way that breaks in 6.7.0, although I'd love to be able to fix it.

To be able to continue, could you explain & show in which situation this fails? Thanks!

**Comment by francisrod01** [comment]
Thanks for reaching out!
I'm implementing server-side rendering for the InstantSearch component.

```js
<InstantSearch
  indexName={'....'}
  searchClient={searchClient}
  searchState={restProps.searchState}
  onSearchStateChange={onSearchStateChange}
  createURL={createURL}
  {...restProps}
>
 .....
```

And I call it on the server side:

```js
Search.getInitialProps = async (context) => {
  const { req, res, query, ...restProps } = context;

  const searchState = pathToSearchState(restProps.asPath);
  const resultsState = await findResultsState(SearchApp, {
    searchClient,
    indexName: '...',
    searchState,
  });
  ....
```

And here I have a "proxy" for the `searchClient`, provided for the Algolia's docs:

```js
// Detecting if query is empty (""), then mock an empty response.
const searchClient = {
  search(requests) {
    if (requests.every(({ params }) => !params.query)) {
      return Promise.resolve({
        results: requests.map(() => ({
          hits: [],
          nbHits: 0,
          nbPages: 0,
          processingtimeMS: 0,
        })),
      });
    }

    return searchClientLite.search(requests);
  }
}
```

**Comment by Haroenv** [comment]
Ah, I see in which case params can be absent now, this can be fixed by making `params` optional in the deduplicating.
