### ISSUE TITLE
Recipe: dynamic facetting

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#309]
algolia/instantsearch.js#2071

**Comment by wedneyyuri** [comment]
Related: https://github.com/algolia/dynamic-faceting-guide/issues/13

**Comment by wedneyyuri** [comment]
Please, can you explain why my comment was marked as off-topic? The repository that I referenced is the "suggested way ™" to create dynamic filters today. Unfortunately this solution has problems that as far as I know have not been addressed.

Unfortunately react-instantsearch has no out of the box solutions for dynamic filters, I would be grateful if you could at least consider these scenarios rather than just ignore them.

**Comment by Haroenv** [comment]
Because this issue is about adding a guide, while your comment was about a separate issue with a guide which isn't documented here. Sorry if it came over rude
