### ISSUE TITLE
RefinementList receive wrong intermediate results

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [algolia/react-instantsearch#3127]
**Describe the bug 🐛**

When i call `searchForItems` through a React Effect triggered from a prop change, the refinement list obtain a first intermediate wrong result (non filtered) then receive the correct result.

**To Reproduce 🔍**

1. Go to 'https://codesandbox.io/s/peaceful-hopper-vl2hx?file=/src/App-Multi-Index.js'
2. Type some characters in the input
3. Remark that results are flickering between non search to search
4. Look in console
   1. First we can see the initial result with isFromSearch = True
   2. When we type a character, we got a first result (non filtered) with isFromSearch = False
   3. Then a new re-render occurs with isFromSearch = True

**Expected behavior 💭**

We should not receive the intermediate state with default results from non search.

**Environment:**

 - OS: Windows 10
 - Browser Firefox
 - Version 92.0

Context : 
We manage a search value in "Redux" which will be applied to filter multiple distinct factets.
That is why we are using Props/ UseEffect to trigger a new search from inside the connected component.

Do you have any idea why we got this behavior ? Is calling "searchForItems" from a useEffect is bad ?

Additional notes : 
When I tried the standard `RefinementList`, if any props of the component change, the refinements are reset.

Yours faithfully,
LCDP

**Comment by sarahdayan** [comment]
Hi @LeComptoirDesPharmacies!

There are two different behaviors at play here: **global search**, which looks for items and affects search results, and **search for facet values**, which looks within facets.

When you make a global search (e.g., using the `Searchbox` widget), Algolia returns new search results. It updates the local search state managed by React InstantSearch, and can affect several widgets. For example, if you were using a `Hits` component, items would update. The refinements within a `RefinementList` also update because they reflect the available refinements within the new seat of search results.

When you make a search for facet value (which you get out of the box with the [`searchable`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#widget-param-searchable) option when using the widget's default rendering) you're only searching for facet values for the given attribute _within_ the current search results. This search isn't persisted in the search state, only at the API client level, because as soon as you do another global search, it gets discarded.

In your case, the search query you're forwarding to your custom refinement list triggers a re-render, but before `searchForItems` has had a chance to update `items` (which is asynchronous), the component renders the `items` that are in the search state. If you look closely, the flicker only happens at the second keystroke, and then it always flickers with the initial state. **That's because the search state didn't change internally, and React InstantSearch is re-rendering with those items before the call to `searchForItems` resolves.**

**Could you please give me a bit more context on the experience you're trying to achieve?** There are ways to do what you want, but I'd like to fully understand your end goal to make sure I put you on the right path.

**Comment by LeComptoirDesPharmacies** [comment]
Hi @sarahdayan,

Thanks for this perfect explanation that make the discussed behavior totally understandable.

Here is our use case : 
We have a single `SearchBox` where user can type and we should search in multiple facet values + indexes for every keystroke.
If we take a "books" example :
1. User type 'abc' search
2. We should search :
  - Search 'abc' in 'genre' facet and display labels in a list
  - Search 'abc' in 'author' facet and display labels in a list
  - Search 'abc' in 'books' index and display hits in a list
  - Search 'abc' in 'books_replica' index and display hits in a list
  
This scenario really seems like `autocomplete` feature however we have to search in facet values and we did not find a way to combine index + facet value search with the Instant Search `autocomplete` yet.

We successfully workaround the "reset" behavior by caching facet values found in the component state and replace this state only if "isFromSearch" is "True".

Feel free to give some tips about other ways of accomplish this.
Yours faithfully,
LCDP

**Comment by sarahdayan** [comment]
Hey @LeComptoirDesPharmacies, this indeed is a typical autocomplete scenario.

We recently released a new version of our [Autocomplete](https://github.com/algolia/autocomplete) library, which makes it trivial to search in multiple sources at once. It notably provides a `getAlgoliaResults` and a `getAlgoliaFacets` functions to easily retrieve each.

If you're interested in looking into it, here are a couple of interesting links:

- [What is Autocomplete?](https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/)
- [Including Multiple Result Types](https://www.algolia.com/doc/ui-libraries/autocomplete/guides/including-multiple-result-types/)

Since you're using React, you can either integrate `autocomplete-js` with React (see [this guide](https://www.algolia.com/doc/ui-libraries/autocomplete/guides/using-react/)) or [create a fully custom renderer](https://www.algolia.com/doc/ui-libraries/autocomplete/guides/creating-a-renderer/). **The latter is only recommended if you need to have complete control over the rendering of the entire experience.** When using the former, you can fully customize the rendering of the panel and source, but you don't have access to the searchbox.

Note that we recommend using the Autocomplete library over the `<Autocomplete>` widget from React InstantSearch.

**Comment by LeComptoirDesPharmacies** [comment]
Hi @sarahdayan,

Nice to hear that you recently released a new version for your Autocomplete library with "getAlgoliaResults" and "getAlgoliaFacets" which seems perfect for our use case !

It seem that your "Autocomplete" component can send facet value search + index search in one single query/request.
Is that true ? If yes, it could save us tons of request count !

Yours faithfully,
LCDP

**Comment by francoischalifour** [comment]
Hey @LeComptoirDesPharmacies! Yes, Autocomplete batches both facet index and regular index queries in a single network request 🙂

**Comment by sarahdayan** [comment]
Just make sure you're using the same `algoliasearch` client instance and all requests to Algolia will be batched 👍

**Comment by LeComptoirDesPharmacies** [comment]
Wow, that is such a brilliant works that you did with this "new" autocomplete version. 👍 
I am currently modifying our application to use it with `createAutocomplete` (because we need to customize the SearchBox) and results are amazing !

**Note for those who read this thread :** 
For better readability and to be aligned with how React Instant Search works, we put the `autocompleteState` in a React Context and we use it in our children through Redux Selector (Select in React Context to avoid useless re-rendering).
This way, we have created some custom mirroring connectors (ex : `connectSearchBox`, `connectHits`, ...) that receive props from `autocomplete` state instead of `InstantSearch` state.

Ex : 
```
const ConnectedSearchBox = connectSearchBox(
  ({ setQuery, setIsOpen, ...rest }) => {
    return (
      <SearchMenu
        onFocus={() => setIsOpen(true)}
        onSubmit={() => setIsOpen(false)}
        onSearch={setQuery}
        {...rest}
      />
    );
  },
);
```

Yours faithfully,
LCDP
