### ISSUE TITLE
How can I run the e-commerce example locally?

### ISSUE THREAD

**Issue by jeffersondarcy** [algolia/react-instantsearch#3138]
I haven't figured out yet

**Comment by Haroenv** [comment]
I took the example, added react-scripts as a dev dependency and then it worked on codesandbox. It's more meant as an example of what code to use than to be put directly in production though. Regardless of that, we should have a good example to start with online somewhere (otherwise we also have these examples: https://instantsearch-templates.netlify.app).

Here's the working sandbox: https://codesandbox.io/s/dreamy-dew-9rb4m?file=/package.json

**Comment by jeffersondarcy** [comment]
thanks @Haroenv - locally would be better, but codesandbox is an option

**Comment by Haroenv** [comment]
If you do a new create react app (or any other setup) and copy all the code in it, it should work as a workaround @jeffersondarcy

**Comment by sarahdayan** [comment]
@jeffersondarcy You can export CodeSandbox sandboxes to test them locally.

![Capture d’écran 2021-10-01 à 15 48 14](https://user-images.githubusercontent.com/5370675/135631014-74f32eb6-e8e4-48fb-8148-89d66c5d6e22.png)

**Comment by jeffersondarcy** [comment]
thanks @Haroenv and @sarahdayan both seem working solutions
