### ISSUE TITLE
Cannot create custom UI for Control and Redo (Maps)

### ISSUE THREAD

**Issue by joshuabaker** [algolia/react-instantsearch#3448]
## Issue

It is currently not possible to control the `enableRefineOnMapMove` properly for `GeoSearch` (e.g. via our own app state).

The geo components don’t export the properties of [`GeoSearchContext`](https://github.com/algolia/react-instantsearch/blob/519887de1b151b442068b3d426a69f9f6c2d4095/packages/react-instantsearch-dom-maps/src/GeoSearchContext.ts) (i.e. `isRefineOnMapMove`, `hasMapMoveSinceLastRefine`, `toggleRefineOnMapMove` and `refineWithInstance`).

This means creating our own UI for `Control` or `Redo` is effectively impossible.

## Additional context

Some common UI libraries don’t compose and style their components in the same way Instant Search does. This makes it impossible to map to certain design systems, at present.

## Possible solution

The simplest solution would be to export the `GeoSearchContext` to allow us to access that context in our own components. 

Alternatively, looking at the possible APIs, these props could be passed/managed via the `connectGeoSearch` somehow, but that seems a lot more complex (also passes complexity to core).

**Comment by Haroenv** [comment]
For the time being, you can import GeoSearchContext from the exact path, right? 

I do agree that we need to rethink what kind of customisation is needed for map applications, and what we have today doesn't address all those use cases. 

If you have ideas on how to take complexity out of this design, we have a new version of React InstantSearch which will soon be released, but doesn't implement any of the geo features yet, you'd use it via `connectGeoSearch`. We'd want to build on top of that in the future but avoid past mistakes. If you have any ideas on how that could be done, we're all ears!

**Comment by joshuabaker** [comment]
Thanks for the speedy response, @Haroenv. 🙏🏻 

I had tried that, but just now realised that my editor automatically imported the CJS build, instead of the ES build. 😵

Regarding customisation, exposing the context would be amazing. Guessing this applies a bit more to the hooks API now, but might make sense to implement in core so all areas can benefit from the same common logic.

**Comment by joshuabaker** [comment]
I spoke too soon. The build fails using the ES module via a direct import.

> SyntaxError: Cannot use import statement outside a module

I thought we could probably import everything manually from the CJS build, but that’s not working either.

Have you seen an exact path import working for `GeoSearchContext`?

**Comment by Haroenv** [comment]
Can you clarify which imports you've tried? Maybe with a reproduction on GitHub we can help you best

**Comment by Haroenv** [comment]
Ah, the issue is actually the opposite and related to how Next is stricter now on what can count as an es module. This means it resolved the cjs version of the main library, and expects the cjs of the individual file too. Locally you can check that by adding logs to the different entry point files and seeing what gets resolved. This means to have the same context, you should use `/cjs/ for the individual import.

https://codesandbox.io/s/zealous-taussig-u6rxit?file=/pages/index.js seems to work in the sandbox at least for me

**Comment by joshuabaker** [comment]
I actually started out with the CJS build. Trying it now locally, the state doesn’t update when toggling the checkbox. This is also true in your sandbox (with a valid Google Maps API key set).

I’m near certain that Next is using the ES build, as I can import it and see it working with the hot module reload. The build fails though, because the package doesn’t include that file/path as an export target.

**Comment by Haroenv** [comment]
It's not ideal, as it forces everything to be CJS, because the React InstantSearch dom maps module hasn't yet been converted to use `type: module` or `exports` with exact paths, unlike some of the other packages, but if you import everything from CJS, you an use the context module.

I would recommend alternatively as well that you could adopt the whole geo-search code base into your own so you can change whatever you please.

Here's a sandbox that shows the toggle working with a "full-cjs setup" https://codesandbox.io/s/zealous-taussig-u6rxit?file=/pages/index.js

**Comment by joshuabaker** [comment]
Yeah, they cannot pass the imperative boundary. That makes sense.

It doesn’t stop us exporting a `GeoSearchConsumer` component though, right? Additionally (or as well as that) we could export a `useGeoSearch` hook that just passes the context state.

**Comment by Haroenv** [comment]
Yes, we could expose the GeoSearchContext
