### ISSUE TITLE
facetFilters is typed incorrectly

### ISSUE THREAD

**Issue by kanehara** [algolia/react-instantsearch#3486]
## 🐛 Bug description

`facetFilters` is typed as `readonly facetFilters?: string | readonly string[] | ReadonlyArray<readonly string[]>`. This does not allow for a combination of AND / OR queries like so: `facetFilters: ['filter1', ['filter1', 'filter2']]`

## 🔍 Bug reproduction

1. Pass `['filter1', ['filter2', 'filter3']]` into `facetFilters` arg
2. Get TS error

## 💭 Expected behavior

`facetFilters` should be typed as `string | (string | string[])[]`

## 🖥 Screenshots
<img width="907" alt="Screen Shot 2022-05-27 at 5 50 01 AM" src="https://user-images.githubusercontent.com/5545166/170702504-d0914976-a0fc-4afc-9fcf-4c10be0300c9.png">

## Environment

- OS: macOS
- Browser: React Native
- Version: ^0.67.3

**Comment by Haroenv** [comment]
Which facetFilters type is it you use?

**Comment by kanehara** [comment]
What do you mean?  I'd like to apply an AND filter in conjunction with an OR filter.  This works against the Algolia API but it isn't typed as being supported.

**Comment by Haroenv** [comment]
Sorry, I meant which code are you running? FacetFilters is defined in many places and I'm not sure which one is incorrect.

Also note that if you're using other widgets like RefinementList, they already use the facetFilters key and will override a parameter set by configure (or maybe get confused by it). If you want to set a standalone filter that doesn't get touched by any other InstantSearch code, `filters` is the best choice.

I'm still interested in knowing which code has that type, thanks!

**Comment by FabienMotte** [comment]
Hey!

We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it. Feel free to reopen it if you still have the type error.

We recommend anyone who is currently using React InstantSearch v6 to [migrate to Hooks](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react-hooks/).
