### ISSUE TITLE
Hits array is not being updated

### ISSUE THREAD

**Issue by vpaul18** [algolia/react-instantsearch#3644]
## 🐛 Bug description

I have been struggling for hours now as to why the hits array passed as props is empty.

## 🔍 Bug reproduction

Here is a full reproduction of the problem I'm facing:

<https://codesandbox.io/s/cocky-snowflake-gni9uf?file=/src/App.js>

## 💭 Expected behavior

I expect the results of the search (each hit) to show up after a keystroke. I am also using the same datasets provided by you, so I'm confident that the data exists.

## Environment

- React InstantSearch Hooks version: "^6.35.0",
- React version:   "18.2.0",
- Browser: Chrome 105. x
- OS: Windows

## Additional context

That would be it! Thanks!

**Comment by VishnuuVijayan** [comment]
I have the same issue, if you give an api call through postman it actually works

**Comment by Haroenv** [comment]
Does this happen with other versions as well?

**Comment by vpaul18** [comment]
@Haroenv  This sandbox seems to work : https://codesandbox.io/embed/kvn0lpp83?codemirror=1 , but If I match their dependencies and imports , I get export errors from the packages.

@VishnuuVijayan  Yes, it does seem to work… when the page rerenders (for example if I change a CSS class) - I can see the hits …

**Comment by sarahdayan** [comment]
Hey @vpaul18, the issue comes from React strict mode usage. It disappears in React InstantSearch [6.37.0](https://github.com/algolia/react-instantsearch/releases/tag/v6.37.0), where we added React 18 strict mode support.

I updated to 6.38.0 and did a couple changes on your sandbox and it seems to work just fine now.

[Updated sandbox ➡️](https://codesandbox.io/s/headless-moon-r617e8?file=/src/App.js)

Note that we're passing `currentRefinement` as the input's `value`, making it controlled. The updated value comes from React InstantSearch, which updates it when using `refine`.

If you want to stay on 6.34.0, you need to drop strict mode (see [here](https://codesandbox.io/s/stoic-engelbart-cfhl1w?file=/src/index.js)
