### ISSUE TITLE
Autocomplete, empty query and slow network. 

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#465]
Context: 

You have an autocomplete using the `connectAutoComplete` connector. 
1. You type one query "a"
2. You removed that query
3. You type another query "b"

On 3, the result of the query "a" or the result of empty query depending of the configuration of your autocomplete will appear first, and then you'll have b. That's producing a flash, and more importantly can be disturbing with slow network. 

![autocomplete-empty-query](https://user-images.githubusercontent.com/6885378/31438807-fbeb7676-ae89-11e7-9c31-e6096fb01229.gif)

The reason behind this is that we do not reset hits to [] each time we perform a query, therefore when doing a new one, you first have the results of the previous query inside the props. This become a problem in case you hide some of the results like here if there's no query entered by the user. 

See: 
https://discourse.algolia.com/t/react-instantsearch-w-autosuggest-unwanted-initial-hit-results-displaying/2495
https://discourse.algolia.com/t/react-instantsearch-v4-1-3-is-out-tada/3167/4

Goal: 

You can make some condition yourself to avoid this behaviour like I did here https://codesandbox.io/s/k9p6y7zllr taking advantage of the `componentWillReceiveProps` lifecycle method. At the bare minimum we should add this in the autocomplete guide. 

I'm also wondering if we could do something inside the library that can prevent this. 

What do you think?

**Comment by oyeanuj** [comment]
@mthuret Also facing this. It seems that the workaround in the codesandbox would work only for initial results but not on change of query. 

Is it possible to either empty the hits (say, if optedIn) or have a status like `isRefined` which would be false when the hits aren't for the `currentRefinement`? This way, users could tailor their behavior - choose to show results regardless and suffer the flicker or show only accurate results and have a second of no results?

**Comment by samouss** [comment]
The proposed workaround doesn't work depending on how you trigger the `refine` & `setState` calls. I have done a [jsFiddle](https://jsfiddle.net/samuel_vllnt/Lbq528v8/) example showing the different downsides of the proposed approach.

**Context**:

1. You type one query "p"
2. You removed that query
3. You type another query "m"

On the first example, everything works. On the second & third example you can observe a blink on the list when the input value pass from empty to something. If you have trouble to see the blink you can emulate a slower connection.

**Explaination**:

- **With plain state**: this is the workaround used in the CodeSandbox. But it only works thanks to a race condition. When the lifecycle `componentWillReceiveProps` is called the state is not correctly set. Since `setState` has been called on the input change event the state should be `"p"` instead of `""`. But it's async by nature, so in that case the workaround works because when the hook is called the state is still an empty string.

- **With state updater**: in this situation we will trigger the `setState` call with [a state updater](https://reactjs.org/docs/react-component.html#setstate) in `componentWillReceiveProps`. As we seen in the previous example `setState` is called on the input change event. So the previous state inside the updater is now correct instead of having `""` we will have `"p"` which is the current state. Then condition is executed and the component will be render the hits of the previous search.

- **With state updater**: in this situation, we call `refine` from the `setState` callback after that we are sure that the state has been correctly update. So even if we don't use the state updater in `componentWillReceiveProps` the state is still correct. As in the previous example the `hits` passed to the components are the one of the previous search.

**Comment by oyeanuj** [comment]
@samouss @mthuret Running into a similar problem with `connectInfiniteHits`. I'd rather show a skeleton loading state while results are being fetched than flicker and back but the connector doesn't pass any loading state.

In both these cases, thoughts on adding an `isFetching` state?

**Comment by Haroenv** [comment]
@oyeanuj, that should be covered by #544 I think

**Comment by oyeanuj** [comment]
@Haroenv So, I think #544 only covers providing a `loading` component and `isSearchStalled` (which I am not sure is the same as loading) to `SearchBox` and `connectSearchBox`. 

@bobylito can confirm?

 I think ideally the `loading` status should be provided to `connectHits`, `connectInfiniteHits`, and `connectAutoComplete`. With that field, I feel like this ticket would have a decent workaround as well.

**Comment by oyeanuj** [comment]
Hi folks - just following up to see if there is any update here or thoughts on what a workaround or solution might be? At the moment, it is the biggest missing element for a smooth experience on our app.

Thanks for all of your work on the library!

**Comment by samouss** [comment]
Hi @oyeanuj, sorry for the delayed answer. 

You are right the `isSearchStalled` is not the same as `loading`, this indicator is pass to true when search as the name suggest is "stalled". It happens after a given delay that can be configured on the `InstantSearch` component. You can find more informations about that [in our documentation](https://community.algolia.com/react-instantsearch/widgets/%3CInstantSearch%3E.html#default-props-entry-<InstantSearch>-stalledSearchDelay).

IMO we don't need to pass additional props to  `connectHits`, `connectInfiniteHits`, and `connectAutoComplete` since we can compose them with [`connectStateResults`](https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html). The latter give you access to the current state of the search, you can find a boolean indicator `searching` on it. So you can use this information for display your skeleton.

Here is a quick example that hide the suggestions when a search is in progress:

```jsx
const AutoComplete = ({ currentRefinement, hits, searching, refine }) => (
  <div>
    <input
      value={currentRefinement}
      onChange={event => refine(event.currentTargert.value)}
      placeholder="Type a product"
    />
    <div hidden={searching}>
      {currentRefinement && (
        <ul>{hits.map(hit => <li key={hit.objectID}>{hit.name}</li>)}</ul>
      )}
    </div>
  </div>
);

const AutoCompleteConnected = connectAutoComplete(connectStateResults(AutoComplete));
```

**Comment by rtman** [comment]
I'm not sure how this is supposed to be used, I've tried the following:
```
export const IsSearching = connectStateResults(({searchState, searchResults, searching}) => {
  if(searching){
    return(
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <Text style={{color: Colors.primaryTextColor}}>
          SEARCHING
        </Text>
        <Spinner isVisible={searching} color={Colors.secondaryColor} type='Bounce'/>
      </View>
    )    
  } else {
    return(
      null
    )
  }
})
```

The spinner or text never show up. When exactly does this searching prop go true? I'm trying to use it in a search component so I thought that as I type in a search I would see it. Perhaps the network is too fast for it to show? I'm also trying to get rid of the flicker discussed above.

**Comment by rtman** [comment]
I'm finding the above method works, but causes additional flickering due to `searching` seeming to turn on and off a few times during typing in a search. Is there anyway to smooth this out?

**Comment by oyeanuj** [comment]
@samouss thank you for the workaround! and i had the same experience & thought as @rtman's comment above.

**Comment by samouss** [comment]
Hi @oyeanuj @rtman

We found another solution without the flickering effect. At the end what we want to display is only the results that match the `currentRefinement`. Inside the `searchResults` we have access to the state of the query. So we can check if the `currentRefinement` match the `query` of the current `searchResults`. We made an example [on CodeSanbox](https://codesandbox.io/s/x7x6826xmp) with & without the condition, it's easier to see the difference with a network throttling. On the first example the previous results is immediately displayed when we start typing. But on the second one the results appear only when the `currentRefinement` match the `query` of the current `searchResults`.

Here is a quick example:

```jsx
class AutoComplete extends Component {
  state = {
    hits: this.props.hits
  };

  componentWillReceiveProps(nextProps) {
    const { currentRefinement: nextRefinement, hits, searchResults } = nextProps;
    const { currentRefinement } = this.props;

    const hasMatchingResults =
      !!searchResults &&
      !!searchResults.query &&
      currentRefinement.startsWith(searchResults.query);

    this.setState({
      hits: hasMatchingResults && !!nextRefinement ? hits : []
    });
  }

  render() {
    const { currentRefinement, refine } = **this.props;**
    const { hits } = this.state;

    return (
      <div>
        <input
          value={currentRefinement}
          onChange={event => refine(event.currentTarget.value)}
          placeholder="Type a product"
        />

        <ul>
          {hits.map(hit => (
            <li key={hit.objectID}>
              <Highlight attributeName="name" hit={hit} />
            </li>
          ))}
        </ul>
      </div>
    );
  }
}

const AutoCompleteConnected = connectAutoComplete(connectStateResults(AutoComplete));
```

**Comment by oyeanuj** [comment]
@samouss Two question here: Do you think the `currentRefinement` could ever be made available within `connectStateResults`? Currently, I have my search box in a different component connected with `connectSearchBox`, and results in a different sibling component, and at every place there is little logistical tediousness connecting the two components.

Also, any other thoughts on a solution for this problem?

**Comment by sarahdayan** [comment]
This should be fixed now.

Also today, we recommend using the [Autocomplete](https://github.com/algolia/autocomplete) library instead of `connectAutocomplete`.
