### ISSUE TITLE
Create an analytics widgets

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#520]
See `instantsearch.js` for the behaviour

**Comment by jagwire16** [comment]
I would love to see an analytics widget for react-instantsearch. Specifically, I want to use the analytics data to put it through a deep learning system like TensorFlow to improve the ordering of results for specific queries.

**Comment by wub** [comment]
Any updates on this?

**Comment by sarahdayan** [comment]
The `analytics` widget from InstantSearch.js was deprecated in favor of the Insights middleware. You can see how to set it up with React InstantSearch [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/send-insights-events/react/).

Since React InstantSearch will soon be replaced by React InstantSearch Hooks, we strongly recommend [upgrading](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react-hooks/) then using the Insights guide for [React InstantSearch Hooks](https://www.algolia.com/doc/guides/building-search-ui/going-further/send-insights-events/react-hooks/).
