### ISSUE TITLE
Searchstate reset after closing the dialog that hosts your refinementList

### ISSUE THREAD

**Issue by alexofob** [algolia/react-instantsearch#540]
Hi there,

My use case is for mobile web application.

Because mobile screen is small, it is not possible to show refinementlist widget and the searchresults all in the same page.

So, I show only the searchresults (hits) on the page and keep a button which onclick will open a dialog to help you refine the search using the refinementlist.

(I am using redux in a controlled manner to apply searchstate. ie I am using searchstate and onsearchstatechange parameters on my instantsearch widget.)

However, when I have closed the dialog - expecting the searchstate will be maintained and apply the refinement (as searchstate) to my instantsearch results - the searchstate is rather reset and the state which was changed by the refinementlist dialog is lost.

(What is striking is that my redux searchstate item remains unchanged, and it is as if my controlled searchstate is not working. You typically expect that your redux state will reflect the instantsearch search state when you have connected them as described above)

How can I maintain the state in the dialog created via the refinementlist and have applied to my instantsearch results when I have closed the dialog and the refinementlist contained in it has been closed.

I am raising this issue here as from discourse I understand it has been raised many times and there is no fix yet.

Thanks.

**Comment by samouss** [comment]
Hi @alexofob,

In order to apply a refinement the widget must be mount. In your case, when you close the modal your widget is unmount and you lose the refinement. 

The solution to this is virtual widgets, you can follow a guide [in our documentation](https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#putting-our-filters-in-a-modal) for implement this behaviour.

Let me know if you still have trouble with your implementation.

**Comment by alexofob** [comment]
Hi @samouss,
Many thanks for the feedback. I get the concept so I will implement and feedback on the results.

BR
Alex

**Comment by alexofob** [comment]
Hurray,
@samouss 
It works like a charm.
Thanks.
