### ISSUE TITLE
Allow to pass min or max for defaultRefinement in connectRange

### ISSUE THREAD

**Issue by samouss** [algolia/react-instantsearch#564]
With the current implementation of `connectRange` we force the user to pass `min` & `max` inside the `defaultRefinement`. The widget works correctly but React trigger a warning because of the `PropTypes`. We should allow to pass `min` or `max` only inside the `defaultRefinement`.

```jsx
<RangeInput
  defaultRefinement={{
    min: 5
  }}
/>
```

Trigger this warning:

```
Warning: Failed prop type: The prop `defaultRefinement.max` is marked as required.
```

**Comment by Haroenv** [comment]
I think we need to do it like this: https://github.com/facebook/react/issues/5916

**Comment by samouss** [comment]
I think I have not correctly expose the problem, inside the `defaultRefinement` we can pass both property `min` & `max`. We should also allow the user to pass on of the two if needed. This declaration should be sufficient:

```js
const propTypes = {
  defaultRefinement: PropTypes.shape({
    min: PropTypes.number,
    max: PropTypes.number
  })
}
```

**Comment by Haroenv** [comment]
```js
const propTypes = {
  defaultRefinement: PropTypes.oneOfType([
    PropTypes.shape({
      min: PropTypes.number,
      max: PropTypes.number,
    }),
    PropTypes.shape({
      min: PropTypes.number,
    }),
    PropTypes.shape({
      max: PropTypes.number,
    }),
  ]),
};
```

like this I meant

**Comment by denkristoffer** [comment]
I'm here from https://github.com/algolia/react-instantsearch/issues/892 — the solution offered to the problem there works well with `connectRefinementList` as it takes an empty array as a value. Not so for `connectRange`, since it doesn't allow for `undefined` to be used as a `defaultRefinement`. However, the way I see it, to allow for the default, blank `connectRange` behaviour, it would actually have to allow both `min` and `max` to be `undefined`, no?

**Comment by samouss** [comment]
@denkristoffer Yes you are right. The shape of the `propTypes` should be:

```js
const propTypes = {
  defaultRefinement: PropTypes.shape({
    min: PropTypes.number,
    max: PropTypes.number
  })
}
```
