### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by FDiskas** [algolia/react-instantsearch#577]
Please add typings for TypeScript
**Do you want to request a *feature* or report a *bug*?**
FEATURE

**Comment by Haroenv** [comment]
Some inspiration from other react libraries: 
* [react-router](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts)
* [react-stripe-elements](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/947a8fb761e66f73a6750c7fd924a0e2aff0c2d5/types/react-stripe-elements/index.d.ts)

Feel free to get started with it @FDiskas, it's not exactly a priority for us, since this is the first request for it AFAIK, but we will definitely help out with validating. Maybe something can be done to convert proptypes to TS definitions?

**Comment by Haroenv** [comment]
https://yarn.pm/react-to-typescript-definitions can be tried

**Comment by mthuret** [comment]
@alexandremeunier you might have something to share here :)

**Comment by romainquellec** [comment]
Is there any news/improvement on Types with Typescript ?

**Comment by Haroenv** [comment]
There's an open PR for using a tool to generate typings, but it didn't completely work. Feel free to contribute @romainquellec :) https://github.com/algolia/react-instantsearch/pull/701

**Comment by gburgett** [comment]
Hi All,  I've opened a PR to DefinitelyTyped with definitions for the types that we've been maintaining in our repo.  You all could use it as a base to build out the rest of the type definitions.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29793

**Comment by Haroenv** [comment]
Thanks @gburgett, that's definitely a solid start for typings! We will take a look and see if there's any missing things. 

I see you're documenting internals as well, is that because you use them, or because you simply wanted to add typings for everything?

**Comment by samouss** [comment]
Thanks a lot @gburgett I'll review the PR and probably fill the missing types next week.

**Comment by gburgett** [comment]
Hi @Haroenv , I'm not sure which of them were internals.  I've definitely reworked the definitions since getting feedback from the DefinitelyTyped folks, are they still exporting internal functions?

**Comment by Haroenv** [comment]
I didn’t mean that in a way that they shouldn’t be documented, but e.g. createInstantSearch usually isn’t necessary to use, unless you’re targeting something which isn’t web, and isn’t react native either. 

In definitely typed they seem to want everything documented, so that was a good call from you to make it complete!

**Comment by ivawzh** [comment]
Definitely need more types. Currently, the amount of `any` and the lack of generic type that defines results is really bad.

**Comment by Haroenv** [comment]
@ivawzh the typings are open source and not maintained by us. Feel free to contribute: 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-instantsearch-core
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-instantsearch-dom

**Comment by ivawzh** [comment]
Big disappointment to Algolia's strategy and altitude.

You are asking the paid customers to create and maintain the for-profit products you sell. 

Say even if I maintain the types for you, how will they get up-to-date whenever you deliver changes if you don't take the ownership yourself. 

This is also ignorant of your competitors' standard. Have a look at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/elasticsearch/index.d.ts. They are types maintained by Elasticsearch, an open-source competitor that offers free-for-ever community tier. The quality is just too obviously better than what you currently have.

**Comment by samouss** [comment]
Thanks for your interest in the definition file of React InstantSearch! Like @Haroenv said those files are not mainly maintained by us for one simple reason: it takes a lot of time to do it manually. We maintain the definition file for the [Algolia JavaScript client](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/algoliasearch/index.d.ts) but not all the InstantSearch flavors  available (Vanilla, Vue, React). 

We choose another strategy to fill the gap with those definition files. We gradually move our codebases to TypeScript. Which means that the definition files will be automatically generated an officially supported. But this process takes times since it's a gradual migration. Hope you understand our strategy on the topic.

**Comment by jhalborg** [comment]
Any way to follow your progress for the Typescript migration for each of the projects @samouss ?

**Comment by francoischalifour** [comment]
This is not totally representative but the GitHub language repartition is an indicator of the TypeScript migration progress:

![React InstantSearch languages](https://user-images.githubusercontent.com/6137112/67024259-66e5a500-f104-11e9-8c37-d9949bbebf59.png)

We'll be explicit about the TypeScript definitions once they are available in a release.

**Comment by digibake** [comment]
Hi. So a few years have passed. Are there any further development plans to support typescript?
I know it's a pain to do, but I'm sure it would be well received.

**Comment by ACPK** [comment]
@samouss - Any updates on this?

**Comment by ACPK** [comment]
> Thanks for your interest in the definition files of React InstantSearch! Like @Haroenv said those files are not mainly maintained by us for one simple reason: it takes a lot of time to do it manually. We maintain the definition file for the [Algolia JavaScript client](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/algoliasearch/index.d.ts) but not all the InstantSearch flavors available (Vanilla, Vue, React).
> 
> We choose another strategy to fill the gap with those definition files. We gradually move our codebases to TypeScript. Which means that the definition files will be automatically generated and officially supported. But this process takes times since it's a gradual migration. Hope you understand our strategy on the topic.

@samouss - Hope you had a nice weekend! Would it be possible to update the link in the quoted text?

**Comment by ACPK** [comment]
@samouss  - I hope you had a nice weekend, and any updates on this? Big congrats for updating the Algolia Javascript to use Typescript natively (link[https://github.com/DefinitelyTyped/DefinitelyTyped/commit/7f4291f48b6eea140195d92a8b98902b9b10cf0b)!

**Comment by Haroenv** [comment]
@ACPK to focus our efforts, we have migrated InstantSearch.js (the vanilla.js) version completely to TS first, which is done now. Currently we are working on writing a new version of React InstantSearch using hooks, which internally is based on InstantSearch.js and supports typescript out of the box. You can follow along on [#2870 ](https://github.com/algolia/react-instantsearch/issues/2870#issuecomment-946775130)

**Comment by sarahdayan** [comment]
React InstantSearch Hooks is globally available now and will soon replace React InstantSearch. You can follow the [upgrade guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react-hooks/) to migrate and benefit from first-class TypeScript support.
