### ISSUE TITLE
Basic props for Hits with hitComponent

### ISSUE THREAD

**Issue by davidsonsns** [algolia/react-instantsearch#650]
**Feature: Insert basic prop for Hits?**
Because the component Hits applies only class attribute with the .ais-Hits__root value and does not apply any basic properties like styles or classes. Applying styles can be a bit more labor intensive.

I suggest applying at least these features.
If everyone agrees, you can give me this update, I'll be happy to contribute.

**Comment by samouss** [comment]
Hi @davidsonsns,

If I correctly understand your request, you want to be able to pass custom classes and styles to the root `<div>` of the `Hits` component right?

If I am correct, you will see that every widgets in React InstantSearch has pretty much the same behaviour regarding styling (for now at least). You can't pass custom styles & classes to it, the only way to add style on a widget is to apply styles to [the exposing classes](https://community.algolia.com/react-instantsearch/widgets/Hits.html#classnames).

But you can have a full control of what is render with the [connector API](https://community.algolia.com/react-instantsearch/connectors/connectHits.html). Since you can render whatever you want we don't provide a lots of props related to styles on the widgets.

**Comment by davidsonsns** [comment]
I just thought it would be a good option. But I understood the purpose of the connectors.
Tks.

**Comment by samouss** [comment]
Maybe it will change in the future, we already have a lot of discussion about that (see https://github.com/algolia/react-instantsearch/issues/263)

I'm closing this issue, feel free to reopen it if needed 😉
