### ISSUE TITLE
Search State Parameter

### ISSUE THREAD

**Issue by flouc001** [algolia/react-instantsearch#86]
# Question
I have a React+Redux application where I reproduce search state from a query URL. It seems passing this search state to the InstantSearch component is not sufficient enough to reproduce the search. Do I need to use virtual widgets to reproduce the refinements? If so this seems a bit clunky as I'll have to have many virtual widgets each reproducing refinements. Also if this is the case you may want to update the documentation on [Search State](https://community.algolia.com/react-instantsearch/guide/Search_state.html) to explicitly state widgets/virtual widgets must be present for the refinements.

**Comment by mthuret** [comment]
Hi @flouc001 

You're right, the search state himself it's not sufficient for Instant Search to make the correct request. For that you need the corresponding widget to be mounted (either regular or virtual if you don't want any rendering). That's because each widget contains the search business logic, including what search parameters to set. 

We should definitely make our guide clearer about that if that's not mentioned anywhere. 

Thanks for reporting this.

**Comment by Haroenv** [comment]
You could also use [Configure](https://community.algolia.com/react-instantsearch/widgets/Configure.html) to set refinements manually, that should send a request automatically.

**Comment by mthuret** [comment]
@Haroenv Actually if the refinement is something covered by a widget, it's easier to use it directly. 
For the rest of the search parameters that are not covered, then `<Configure/>` should be used.

**Comment by flouc001** [comment]
Thank you for your suggestions!

**Comment by Haroenv** [comment]
This issue seems to have been solved, 

The search state format is explained here: https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#the-search-state-format-explained
