### ISSUE TITLE
cleanUp the searchState from an empty object in a multi index context

### ISSUE THREAD

**Issue by kylepotts** [algolia/react-instantsearch#986]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Using a VirtualMenu with MultiIndex causes error. 

```
indexUtils.js:139 Uncaught TypeError: Cannot read property 'names' of undefined
    at cleanUpValue (indexUtils.js:139)
```

**Bug: What is the expected behavior?**
Error should not be thrown as it causes issues on the page

**What is the version you are using? Always use the latest one before opening a bug issue.**
4.5.1

```
                <InstantSearch
                  appId={ALGOLIA_APP_ID}
                  apiKey={ALGOLIA_SEARCH_KEY}
                  indexName="roles"
                >
                  <Index indexName="names">
                    <CurrentRefinements
                      transformItems={items => items.filter(item => item.public === 'true' || item.public === 'false')}
                    />
                    <VirtualMenu attributeName="public" defaultRefinement={'true'} />
                  </Index>
                  <Index indexName="vendors" />
                  <Index indexName="locations" />
                  <Index indexName="locationTypes" />
```

Thats the code I have. It is connect to an Autocomplete component. When I click on the AutoComplete component that error above shows.

![2018-02-18-132158_2551x621_scrot](https://user-images.githubusercontent.com/188347/36355275-c393d38c-14ae-11e8-9a01-b3f152d79042.png)

You can see here in the breakpoint for some reason my searchState seems to be empty.  I thought it would look something like 

```
const searchState = {
  query: 'ora', //shared state between all indices
  page: 2, //shared state between all indices
  indices: {
    index1: {
      configure: {
        hitsPerPage: 3,
      },
    },
    index2: {
      configure: {
        hitsPerPage: 10,
      },
    },
  },
}
```
The code is breaking because its expecting for the indexes to be in search state, but not sure why those are not there.

**Comment by kylepotts** [comment]
I fixed this with using a 

```
```

**Comment by samouss** [comment]
Hi @kylepotts, I didn't manage to reproduce the error from the code that you gave. Could you provide us a working example it will help a lot. We provide template on [CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch) in order to avoid you the boilerplate part. Thanks!

**Comment by kylepotts** [comment]
@samouss So I can't get it do happen directly but https://codesandbox.io/s/r7o32r6k8n

If you change a piece of code and have it reload you can see the issue occur. 

![screen shot 2018-02-21 at 11 50 51 am](https://user-images.githubusercontent.com/188347/36493400-87f0328e-16fd-11e8-9fa3-72b3adf32b0f.png)

**Comment by samouss** [comment]
Thanks for the example, it helps a lot. 

The issue appear when we unmount a widget inside an `Index` that never have be refined. Since the `searchState` is not always in sync we try to access the `indices` property that doesn't exist yet. 

Here is [an example](https://codesandbox.io/s/934qnlz324) that easily reproduce the issue.
